version: '3.4'

services:
  cowindb: 
    image: mcr.microsoft.com/mssql/server:2019-latest
  cowin.api:
    image: ${DOCKER_REGISTRY-}cowinapi
    build:
      context: .
      dockerfile: Services/CoWin/CoWin.API/Dockerfile
